### ISSUE TITLE
Question: Class definition for HttpConcurrentServer

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/WebGS#8]
Hello James,

you have exported the methods for the class HttpConcurrentServer (/src/HttpConcurrentServer.gs), but i can't find any Class definition in the /src/WebGs.gs file or any hints in the *.sh files.

Did i overlook somethink, is it a default class in GemStone64Bit3.6.6?

Regards
Peter

**Comment by jgfoster** [comment]
That sounds like I removed the class from the image and when it filed out it wasn't in WebGS.file but the method file remained (Jade files out a dictionary but doesn't delete from the directory). I'll investigate further...

**Comment by jgfoster** [comment]
The file was added on 13-Jul-2021 but the class was not added to WebGS.gs, so was never used (it appears to be an attempt at concurrency that was ultimately implemented with LoadBalancer.gs). I've removed the file.

**Comment by PeterMoe** [comment]
Thanx for your fast responds.
